### ISSUE TITLE
Empty Repo

### ISSUE THREAD

**Issue by mukhsadr** [codepath/web102_prework#2]
I was following the instruction for pre-work and Challenge 2 of 7: Review the Starter Code says there should be index.html and game.js files. After I cloned this repo, I could not find those files. Am I doing something wrong or is this repo missing those files?

**Comment by paigethompson150** [comment]
I was having the same issue - I noticed there's a PR that hasn't been merged yet. I think one of the repo creators has to merge it

**Comment by lmreisdorf** [comment]
You can grab the code from the pull request so that you can move forward. I assume they will fix the issue at some point.

**Comment by isaiahamanuel** [comment]
> You can grab the code from the pull request so that you can move forward. I assume they will fix the issue at some point.

Yep I tried approving the PR to see if it would automatically merge, but I ended up just cloning directly from here instead https://github.com/isabel-gwara/web102_prework

**Comment by BeteabTefera** [comment]
> > You can grab the code from the pull request so that you can move forward. I assume they will fix the issue at some point.
> 
> Yep I tried approving the PR to see if it would automatically merge, but I ended up just cloning directly from here instead https://github.com/isabel-gwara/web102_prework

Perfect Thanks

**Comment by karencarreon** [comment]
files merged!
